### ISSUE TITLE
Assests should be loaded over HTTPS

### ISSUE THREAD

**Issue by nogweii** [planetruby/gems#13]
I have a plugin installed, [HTTPS Everywhere](https://www.eff.org/https-everywhere) that ensures that every request to *.github.io is over HTTPS and not HTTP. Combined with Firefox's default of not loading unsafe assets over HTTP when browsing HTTPS, the gem of the week page looks a bit bland:

![https_errors_planetruby_gems](https://cloud.githubusercontent.com/assets/14547/6531829/69beb8d0-c3f9-11e4-9291-0780c0b16351.png)

**Comment by geraldb** [comment]
Thanks for reporting. Not sure what I can do. It's a static site generated w/ Jekyll. Cheers.

**Comment by geraldb** [comment]
The website has been rebuilt / redesigned - can you try / check again if you find any errors over HTTPS?

**Comment by nogweii** [comment]
No errors any more!

I do notice that the canonical URL is set to HTTP from the SEO plugin. However, Github Pages will redirect HTTP to HTTPS, so it probably isn't that big of a deal.
