### ISSUE TITLE
Ruby/Rails Push Notifications and SEO Friendly gems

### ISSUE THREAD

**Issue by calonso** [planetruby/gems#14]
Hi @geraldb I've developed a pair of gems (rails and standalone ruby) to make it easier to send push notifications to iOS, Android and Windows Phone devices, do you find them interesting to be added to your planetruby gems list? (https://github.com/calonso/ruby-push-notifications)

I also have another very interesting SEO one, which basically allows users to convert absolutely any url in their projects into a SEO Friendly one. (https://github.com/calonso/rails_friendly_urls)

**Comment by geraldb** [comment]
Hello, @calonso,  thanks for your interest. The Gem of the week series is an article series, thus, you're welcome and invited to introduce the ruby-push-notifications gem or the rails_friendly_urls gem by writting an article (or two) for the series.  See all the articles as examples here -> https://github.com/planetruby/gems  A article is really just a simple text file in Markdown. Cheers.

**Comment by geraldb** [comment]
Sorry that the gem of the week series stopped sometime in 2015 - All the best for the new year. Prosit 2021!
