### ISSUE TITLE
Day 10 - 25 Days of Ruby Gems

### ISSUE THREAD

**Issue by rlgreen91** [planetruby/gems#18]
Hello!

I'd love to participate in your Ruby Advent Calendar 2020 activity next month!  I'd like to write an article about the gem [Parslet](http://kschiess.github.io/parslet/), a gem that allows you to build a PEG parser and transformer.  If possible, I'd like to submit my article for Day 10.  

Would a Medium article be acceptable?  I plan to write a small tutorial on how to use it.

**Comment by geraldb** [comment]
You are more than welcome.     Day 10 is yours.    You are welcome to post your article / tutorial anywhere - however, for the advent calendar I need a text file (with formatting conventions in markdown). See as example <https://github.com/planetruby/gems/tree/master/week>. I'm not a medium user - I don't know if you edit / write in medium in Markdown? already or some visual "WISIWIG" editor.

**Comment by rlgreen91** [comment]
Ah, Medium does typically use WYSIWYG editor, but I can write it in Markdown first.  I have a rough outline in my head of the article, and plan to write it this weekend after a good holiday nap.  :)  What day should I have the file to you by?

**Comment by geraldb** [comment]
Sound great. You are more than welcome to publish the article on medium first (no need to hold back / quarantine).   To get your article published here on the advent calendar would be great a day before the deadline (that is, day 10) - I might / will slightly edit to fit the format.  If you want or need I can add you as a team member here on this github org so you can edit / change anytime (inline without pull request) or you point me to a gist or such where I can grab / download the textfile (and optional and possible some images / pictures that go into the i/ folder).      Thanks again. Have a gread weekend.    PS: For the time zone - I'm near Austria's capital in Vienna in Europe - that is 6 hours or such ahead of New York US Time. Greetings from Austria. Prost. Cheers.

**Comment by geraldb** [comment]
@rlgreen91  Hello, a little reminder - 2 days to go! Any news on your Parslet write-up?  As the first contributor your post is especially cherished.  No worries - last minute is ok. Cheers. Prost.

**Comment by geraldb** [comment]
@rlgreen91  Hello, another little reminder - 1 day to go!  Any news? If you need more time - you are welcome to pick a later day.   Good luck. Looking forward to learning more about Parslet. Cheers. Prost.

**Comment by rlgreen91** [comment]
Hi Gerald,

I hope you're doing well.  I'm actually doing one last read through for
the tutorial to make sure it's good to go, but I took a look at the
other posts, and mine seems to be a lot longer.  My tutorial covers a
very basic example, but I do spend time walking the user through how you

might design a parser.  Is that alright?  Or should I alter it to
reflect how the other posts generally go?

Regards,

Rachel

On December 8, 2020, GitHub <notifications@github.com> wrote:
> @rlgreen91 <https://github.com/rlgreen91> Hello, another little
> reminder - 1 day to go! Any news? If you need more time - you are
> welcome to pick a later day. Good luck. Looking forward to learning
> more about Parslet. Cheers. Prost.
>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/planetruby/gems/issues/18#issuecomment-741648011>,

or unsubscribe <https://github.com/notifications/unsubscribe-
auth/AANIKVGNAKAMQTLYRK5ND43ST47H7ANCNFSM4T6ANR2A>.

**Comment by geraldb** [comment]
No worries if it is longer - that's great. A great introduction for a parser even better. Looking forward. No worries about the other articles do your own thing. Thanks for the update.

**Comment by geraldb** [comment]
FYI: I am offline for today (it's 10pm here in Austria). It would be great to publish your write-up tomorrow (Th Dec/10) if you point me to the text source in Markdown (or if you can send in a pull request).  If you publish on Medium I can add the link back to your article (from the version posted here).  Thanks.

**Comment by rlgreen91** [comment]
Ok, I know you probably won't see this until tomorrow morning, but I
will have the PR ready for you.  Hope you have a good night.

Regards,

Rachel Green

On December 9, 2020, GitHub <notifications@github.com> wrote:
> FYI: I am offline for today (it's 10pm here in Austria). It would be

> great to publish your write-up tomorrow (Th Dec/10) if you point me to

> the text source in Markdown (or if you can send in a pull request). If

> you publish on Medium I can add the link back to your article (from
> the version posted here). Thanks.
>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/planetruby/gems/issues/18#issuecomment-742041559>,

or unsubscribe <https://github.com/notifications/unsubscribe-
auth/AANIKVAVDXLOFMFJLYHFYB3ST7PMZANCNFSM4T6ANR2A>.

**Comment by geraldb** [comment]
Sorry no pressure - I moved you to the backup / sunday double list - you can now get your write-up published any later day. Let us know when you are ready - still looking forward learning more about parslet. Cheers. Prost.

**Comment by rlgreen91** [comment]
Oh, sure, no problem.  I have it ready now actually.  Let me upload it.

[Here's a link to the Gist](https://gist.github.com/rlgreen91/2e9f61042233671a307d55bc282472e1).  Let me know if you want me to make some more changes - otherwise, it's ready to go!  Thanks again for letting me participate in this, I really appreciate it.  Hope your week is going well.

**Comment by geraldb** [comment]
Sorry for my misunderstanding.   Looks / reads great.  Thank you!  I try to get it all added to the calendar and published on day 10 in the next hour. Cheers. Prost.

**Comment by geraldb** [comment]
@rlgreen91  Sorry to reopen - I can't find anything about SPQR  (the closest that was making sense was Student Questions for Purposeful Reading  but it's SQPR).   Can you help out, please - what is the spelled out name / meaning for SPQR in your write-up?   Thank you. Cheers.

**Comment by rlgreen91** [comment]
Sorry I didn't see this earlier!  Honestly, there's not really much

about SPQR out there; I don't even know what it stands for.  I just know
that it's a syntax for mathematical notation that can be used in XML
files.  I can't even find a webpage about it - seems to be just one of
those unknown corners that never made it onto the Internet.  I know it's
probably too late to include this in the article but I still wanted to

respond.

Regards,

Rachel

On December 9, 2020, GitHub <notifications@github.com> wrote:
> Sorry no pressure - I moved you to the backup / sunday double list -

> you can now get your write-up published any later day. Let us know
> when you are ready - still looking forward learning more about
> parslet. Cheers. Prost.
>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/planetruby/gems/issues/18#issuecomment-742365450>,

or unsubscribe <https://github.com/notifications/unsubscribe-
auth/AANIKVAJSWNC2Q73BQ4NLXLSUCBDXANCNFSM4T6ANR2A>.

**Comment by geraldb** [comment]
Thanks for clearing the SPQR  mystery up. I will correct the assumed wrong acronym error change the SQPR format in the text simply to XML format and the SPQRParser to Parser.  Sorry for being somehow obsessed with this detail.    Again thanks for your great (parslet) write-up and taking the time. Cheers. Prost.
