### ISSUE TITLE
Day 9 - Ruby Advent Calendar 2020

### ISSUE THREAD

**Issue by picandocodigo** [planetruby/gems#20]
Hi,

I don't know if this fits the content for the Advent Calendar since it's part of my job, but I'm the maintainer of the Ruby Elasticsearch libraries at Elastic and we recently published the [Enterprise Search gem](https://github.com/elastic/enterprise-search-ruby/). Would it be ok to write about this? A brief intro about how it works and a short tutorial on how to interact with the services from Ruby.

I've also written [gamesdb](https://github.com/picandocodigo/gamesdb), a gem to interact with [The GamesDB](http://thegamesdb.net/) API. I'm currently working on version 2.0 with full API support and a few other changes, and hopefully I'll be able to release 2.0 this week.

Would any of these ideas work?
Cheers!

Fernando

**Comment by geraldb** [comment]
Fantastic. Of course. Both work.   You are welcome to pick / claim two days as you like - let me now if you pick one or better two :-).    No worries they demand is not so great and I have to fill up / write up about 10+ days anyway.   Your support and contributions greatly welcome.    Ideally two days one with the elastic gem and the other the gamesdb gem.    Anyways, let me know what works for you and pick a day or two :-).  Greetings from Vienna, Austria. Cheers. Prost.

**Comment by picandocodigo** [comment]
Hi Gerald, that's great! Thanks.

I can do a day next week for elastic/enterprise-search, December 2 or December 3 work for me, let me know which one is better.

And then I can write about gamesdb for the following week, maybe December 9?

Greetings from Edinburgh, Scotland :wave:

**Comment by geraldb** [comment]
Fantastic I put you down for December 2nd and December 9th.   If it gets to tight you are welcome to move back (unless the day is claimed).    Again thanks for contributing.  You can send me a link to a gist or to github page or you can send in a pull request or ... whatever works for you.  The articles are all in markdown and optional you can add images too (that will get copied in the /i folder).  Cheers. Prost. PS: You are welcome to repost the articles  - no exclusive claim here.

**Comment by picandocodigo** [comment]
Great! Are there any guidelines I should follow as to min/max words or anything else?

**Comment by geraldb** [comment]
Not really - you can go as long as need / want. For 10+ examples from the Gem of the week series, see <https://github.com/planetruby/gems/tree/master/week>.

**Comment by picandocodigo** [comment]
@geraldb I wrote a draft for the enterprise-search gem post here in case you want to review it:
https://gist.github.com/picandocodigo/5c8a06b7f110973125597335059b254d

Let me know what you think and I'll confirm the final version by Monday at the latest.

**Comment by geraldb** [comment]
Sorry for not being much help. No worries.  Yeah your post looks great from my quick read. Thanks again for contributing.

**Comment by picandocodigo** [comment]
@geraldb Thanks! Yeah, I will add a couple of screenshots :+1:

**Comment by picandocodigo** [comment]
![image](https://user-images.githubusercontent.com/689327/100528512-b5091b00-31d5-11eb-9502-ba7fa8a90b48.png)


![image](https://user-images.githubusercontent.com/689327/100528508-af133a00-31d5-11eb-92b2-0fe88265fabe.png)

**Comment by geraldb** [comment]
Thanks for the update.  Looking great.

**Comment by geraldb** [comment]
Since you have two articles / post - I am not sure if you are interested - you are of course more than welcome to join the planetruby (github) org than you can edit "inline" in the repo here as committer - let me know and I send you the invite via github.   Cheers. Prost.

**Comment by picandocodigo** [comment]
@geraldb sure! I updated the gist to include the images, but I can also make a Pull Request to the repo if you let me know where the post should be. Thanks!

**Comment by swanson** [comment]
@picandocodigo please make a PR to the `_drafts` folder (you can see several examples there for how to format). You can add the image to that folder as well. Thanks!

**Comment by geraldb** [comment]
Pull request would be great into _drafts otherwise I cut-n-paste on Dec/2 (tommorrow) the source and the images. Thanks again.

**Comment by picandocodigo** [comment]
Done! I'll have the `gamesdb` post ready for review this week :+1:

**Comment by geraldb** [comment]
Your second post is now live, see <http://planetruby.github.io/gems/2020/09-thegamesdb>.  Thanks again for your great write-ups. Keep it up. Cheers. Prost.
