### ISSUE TITLE
Day 20 - Ruby Advent Calendar 2020 - LHS and LHC

### ISSUE THREAD

**Issue by marcoroth** [planetruby/gems#24]
Hey there 😊 

I came across the two gems [`LHS`](https://github.com/local-ch/lhs) and [`LHC`](https://github.com/local-ch/lhc) at a local Ruby Meetup pre-covid. I used them in a handful of projects since and really think they deserve more attention - because they are awesome and not well-known! Let me know if you think they fit in the Ruby Advent Calendar theme. 

Cheers, Marco

**Comment by swanson** [comment]
Marco -- these would be great, maybe pick one and do a write-up?

**Comment by marcoroth** [comment]
Sure! I thought it would make sense to combine them into a single write-up, because `LHS` depends on `LHC` and thus they are very similar.

**Comment by swanson** [comment]
Ideally we would do one gem per day, but if they are intended to be used together than I think one combined post is okay too.

**Comment by geraldb** [comment]
Yes, sure a gem "family" for a post works great too. Please, do. Your write-up on LHS and LHC more than welcome. Please, let us know what day to put down on the calendar.  Welcome.

**Comment by marcoroth** [comment]
If it's fine I'd like to claim the 20th or 21st of December

**Comment by swanson** [comment]
I'll put you down for the 20th, please feel free to submit whenever you've got the post done so we can review. Thanks!

**Comment by geraldb** [comment]
@marcoroth   Litter reminder - 5 days to go!  Any updates on your LHS and LHC write-up?

**Comment by marcoroth** [comment]
Thanks @geraldb for the reminder. I planned to work on it on Friday, so I can open the PR by Saturday at the latest. Or do you need it earlier?

**Comment by geraldb** [comment]
Thanks for the update.  Great plan. No worries.  Saturday  (or last minute) is all ok / fine.  Looking forward, Thanks again.
