### ISSUE TITLE
Day 22 - active-record-events - Ruby Advent Calendar 2020

### ISSUE THREAD

**Issue by pienkowb** [planetruby/gems#29]
Hello! 👋

I'd be glad to participate in the Ruby Advent Calendar 2020 and write about a gem I've created called [active-record-events](https://github.com/pienkowb/active_record-events).
By adding convenience methods on top of a `datetime` field, the gem allows you to manage custom timestamps in a similar way to how ActiveRecord handles the `created_at` and `updated_at` fields.

Would this be a good fit? 🙂 If so, I'd like to claim Day 22.

**Comment by swanson** [comment]
Sounds good, day 22 is yours! Please see the `drafts` folder of this repo for examples of the writeup. Thanks!

**Comment by geraldb** [comment]
Fantastic. Welcome. Day 22 is yours. Cheers. Prost.

**Comment by geraldb** [comment]
@pienkowb  A little reminder - 7 days to go!  Any updates on your active-record-events gem write-up?

**Comment by pienkowb** [comment]
Hi @geraldb! I already started writing the article. I'm planning to finish it this weekend. What's the deadline? Dec 21st?

**Comment by geraldb** [comment]
Thanks for the update. Great plan. There is no deadline (last chance is Dec/24th).  Sorry - no pressure.  Last minute is ok / fine. Looking forward. Thanks again for taking the time to highlight the active-record-events gem. Cheers. Prost.
