### ISSUE TITLE
Day 4 - Noticed gem

### ISSUE THREAD

**Issue by excid3** [planetruby/gems#30]
I built Noticed this year as a way to standardize delivery of notifications in Rails. https://github.com/excid3/noticed

It got 900 stars in just a couple months which is crazy. Definitely is something the community is looking for it seems. Thought it would be a good fit for this.

**Comment by swanson** [comment]
I will pencil you in for Day 4

**Comment by geraldb** [comment]
Fantastic. Thanks you. Welcome. Day 4 is yours.

**Comment by swanson** [comment]
Closed by #39
