### ISSUE TITLE
Day 8 - ActsAsTenant

### ISSUE THREAD

**Issue by excid3** [planetruby/gems#31]
I recently revived the ActsAsTenant Gem (https://github.com/ErwinM/acts_as_tenant) and would like to share it. There are a lot of fixes and improvements that I've added. Plus there are some interesting things to talk about like how to revive an old project and become the maintainer.

**Comment by swanson** [comment]
:+1:

**Comment by geraldb** [comment]
Fantastic. Thanks again for highlighting ActsAsTenant.  Day 8 is yours. Welcome. Cheers. Prost.

**Comment by swanson** [comment]
Closed by #39
