### ISSUE TITLE
Day 11 - BoringGenerators gem

### ISSUE THREAD

**Issue by abhaynikam** [planetruby/gems#35]
Hey 👋 

I wrote a gem called boring generators which intents to generates the basic configurations and reduce the time taken in doing boring setup in a Rails application. The gem uses Rails generators. 

Here is short blog I wrote behind my motivation and problem I wanted to solve using the gem: https://www.abhaynikam.me/posts/introducing_boring_generators/

Hope this fit the requirement here. Please feel free to close the PR if it doesn't 😊 

GEM URL: https://github.com/abhaynikam/boring_generators

**Comment by swanson** [comment]
I think that would be great to include: could you send a PR to add a writeup (see the `_drafts` folder for examples on format)? You can use the same content from your blog post. I will give you Day 11 if that's okay!

**Comment by abhaynikam** [comment]
Day 11 sounds good to me. Thank you @swanson 🎉

**Comment by geraldb** [comment]
Welcome. Thanks - yeah you are more than welcome to (re)use your post for day 11 - BUT yes, it's not a link blog, thus, we would need the markdown source to (re)publish here (and link back to the original) with some edits (header / footer to fit the format).  Cheers. Prost.

**Comment by abhaynikam** [comment]
Sure @geraldb 👍. I am on it. Will send a PR soon.

**Comment by geraldb** [comment]
No pressure.  10 days to go :-). Thanks. Cheers.
