### ISSUE TITLE
Day 12 - Matestack Ui Core

### ISSUE THREAD

**Issue by jonasjabari** [planetruby/gems#36]
Hey!

I've started building https://github.com/matestack/matestack-ui-core 2 years ago in order to escape the frontend hustle when creating reactive web apps based on Rails. My team and me built quite a few producion apps on top of it already and are super happy with the project, cause it enables us to create reactive web apps in pure Ruby! I would love to share it with more Ruby developers out there. :)

Would that be a good fit for the advent calendar?

Happy to hear your feedback!

Cheers!

**Comment by pascalwengerter** [comment]
Working on a PR for this one @jonasjabari 🙌

**Comment by geraldb** [comment]
Yeah. You are more than welcome. Day 12 is yours. Cheers. Prost.

**Comment by pascalwengerter** [comment]
Thanks @geraldb, just opened #37

**Comment by geraldb** [comment]
Thanks I updated the by-line (the written by line ). Thanks again. Great stuff. Cheers. Prost.

**Comment by pascalwengerter** [comment]
Damn, pushed that a second to late after realizing I've missed it ;) thanks, again!

**Comment by pascalwengerter** [comment]
@geraldb no pressure but this one can be safely closed I think :)

**Comment by geraldb** [comment]
Again thanks for the write-up.
