### ISSUE TITLE
Day 17 - any_login

### ISSUE THREAD

**Issue by igorkasyanchuk** [planetruby/gems#41]
Hi,

Please check one of my gem https://github.com/igorkasyanchuk/any_login. Can't imagine any project development without it. This is also one of the favorite gems of our QA team. It can just let you log in as any user in your app in development mode and quickly switch users.

Thanks!

**Comment by swanson** [comment]
Sounds good, I will mark you down for Day 17. Please send a PR with a writeup about this gem (how it works, example, etc) to the `_drafts` folder (you can see some examples of the desired formatting there). Thanks!

**Comment by igorkasyanchuk** [comment]
any_login was created to speed up the development process by allowing developers to quickly log in as any user.
If you using devise for example (or other auth library) you can just add this gem, generate default config, and use. Setup could be done in just a minute.

## Installation

Add AnyLogin to your Gemfile:

``` gem 'any_login'``` and execute in console:

```
 bundle install
```
In application layout (for example `app/views/layouts/application.html.erb`) add the following to the bottom of the page:

```
 = any_login_here if defined?(AnyLogin)
```

Open your app and on the bottom left corner you will see semi-transparent user icon. Click on it and now you can select any user to log in as without a password.

Gem has good documentation and video demonstration.

**Comment by geraldb** [comment]
Since any_login is your gem I assume you have written the readme. You are welcome to use your readme as post, please edit slighty BUT sorry it's up to you hand in the write-up (text file in markdown).

**Comment by geraldb** [comment]
@igorkasyanchuk  A little reminder 2 days to go! Any updates on your any_login write-up? Cheers. Prost.

**Comment by geraldb** [comment]
@igorkasyanchuk   A little reminder 1 day to go!   Your draft posted here looks good - maybe from the readme you can add the tip on how to disable in production and the section on auth gem integratation (devise / authlogic) - You're welcome to cut-n-paste (it's your readme :-).   Looking forward. PS: Would be great if can send in a pull request.   If you need more time,  please say so.

**Comment by igorkasyanchuk** [comment]
Hello @geraldb, just made some modifications to my previous comment and added more information about the gem. I hope it will be enough! Thank you!

**Comment by geraldb** [comment]
Thanks for the update.   I try to to polish the write-up a little tomorrow   - maybe if you don't mind you can add the bonus tip on how to disable in production (from your readme) than I don't have to do it  :-)   Otherwise the (minimum) word count is now good.    I add a link to your great (live) demo app (and source) - or you are welcome to do it :-).    Thanks for the great gem.

**Comment by geraldb** [comment]
FYI: The any_login write-up is now live / published, see <https://planetruby.github.io/gems/2020/17-any_login>. I added some more edits than usual. I hope you like the turbolinks joke / fun. Cheers. Prost.
