### ISSUE TITLE
Day 19 - Addressable

### ISSUE THREAD

**Issue by soulcutter** [planetruby/gems#42]
Reserving the day and committing to writing this.

https://github.com/sporkmonger/addressable

**Comment by swanson** [comment]
Thanks, I will mark you down!

**Comment by geraldb** [comment]
Thanks for highlighting Addressable. Welcome.

**Comment by geraldb** [comment]
Hello, just a reminder - no worries - no pressure - I am happy to publish your write-up once you think it's ready  in any of the upcoming days (left). Last day is the 25th. Again thanks for taking the time highlighting addressable - a fantastic hidden gem. Cheers. Prost.

**Comment by geraldb** [comment]
Thanks your write-up is now published, see <https://planetruby.github.io/gems/2020/21-addressable>.
