### ISSUE TITLE
Day 21 - SuperDiff

### ISSUE THREAD

**Issue by mcmire** [planetruby/gems#43]
[SuperDiff](https://github.com/mcmire/super_diff) is a gem that plugs into RSpec (or can be used standalone) to highlight differences between complex data structures in a more helpful way. It knows how to diff primitives like arrays, hashes, etc. but also RSpec matcher-placeholder objects such as `having_attributes`, Rails model objects, and custom objects.

I'm working on a post for this right now!

**Comment by swanson** [comment]
Sounds good, I'll pencil you in for Day 21. Thanks!
