### ISSUE TITLE
Day 23 - archival_record

### ISSUE THREAD

**Issue by janxious** [planetruby/gems#44]
Reserving the day and committing to writing this.

https://github.com/janxious/archival_record/

**Comment by swanson** [comment]
Got it, thanks!

**Comment by geraldb** [comment]
@janxious   Little reminder - 8 days to go!  Any updates on your archival_record gem write-up?

**Comment by janxious** [comment]
It's on my calendar for writing this week, but I've been distracted because I am covid quarantining right now. 🤷

**Comment by geraldb** [comment]
Thanks for the update. Sorry - no pressure.  Stay healthy.

**Comment by geraldb** [comment]
@janxious  Little reminder - 1 day to go! I hope you're doing well. No pressure.  If you need more time let me know (posting possible until 25th).  Stay healthy. Cheers. Prost.

**Comment by geraldb** [comment]
@janxious   It's your day -  no worries, no pressure - I am happy to publish your write-up up until the 25th.  Let me know if write-up something.  Stay healthy. Cheers. Prost.

**Comment by geraldb** [comment]
The end. Thanks. See you next year. Prosit 2021!
