### ISSUE TITLE
Day 24 - git_reflow

### ISSUE THREAD

**Issue by codenamev** [planetruby/gems#45]
[git-reflow](https://github.com/reenhanced/gitreflow) is a Ruby-based git-server agnostic code workflow assistant. The latest release introduces an easy way to create git commands in Ruby with a number of great helpers to automate as you please.

**Comment by swanson** [comment]
Neat, I'll put you down for Day 24. Please send a PR with a writeup on the gem (how it works, example, etc) to the `_drafts` folder (there are several examples there for guidance on formatting). Thanks!

**Comment by geraldb** [comment]
@codenamev   A little reminder - two days to go!  How's your write-up coming along? Any updates?  Looking forward to publishing and highlighting git-reflow. Cheers. Prost.

**Comment by codenamev** [comment]
Heya 👋  I'll have something to you by EOD.  Thanks for the reminder 😃
