### ISSUE TITLE
pwned Gem - Ruby Advent Calendar 2020

### ISSUE THREAD

**Issue by swanson** [planetruby/gems#46]
Everyone, thanks for your eagerness to participate. We're almost out of slots!

But if you're keen to help, we could use a few backup options in the event that someone is not able to get their post finished in time (totally understandable with the holidays approaching).

If you're interested in writing a backup post, please post here and then submit a PR to the `_drafts` folder with your gem writeup. If we need to swap in your post, we'll have it all ready to go 👍 

And if you don't make it into this year's calendar, there is a "Weekly Gem of the Week" series that is run periodically so we can still use your post later down the line.

Thanks! And happy holidays! 🎄 ⛄

**Comment by swanson** [comment]
@geraldb does sound okay to you to have a couple of backup posts?

**Comment by philnash** [comment]
I meant to open an issue to offer a post on [pwned](https://rubygems.org/gems/pwned/) but I forgot and it seems we're full now. Happy to write one up for a back up post though. Is that ok?

**Comment by geraldb** [comment]
Yeah great idea - the will NOT got to waste if there are any but I add them to the "regular" gem of the week series in january 2021. Cheers. Prost.

**Comment by geraldb** [comment]
Yeah the write-up of pwned more than welcome - in the worst case I publish your write-up here on the "regular" gem of the week series in january 2021 (or before). Welcome. Thanks again.

**Comment by geraldb** [comment]
The new I think better plan is to do double posts on Sundays to get all published in the Advent Calendar 2020. Thanks again for your write-ups.

**Comment by swanson** [comment]
I'd be fine with someone taking my 2nd slot as well if that helps!

**Comment by geraldb** [comment]
@swanson I can swap your slot with on day 7 with @philnash   or you can swap if you like? All fine with me or the "old" idea with double posts / backups as is.

**Comment by swanson** [comment]
I'll leave it to you to run the day-to-day posting and rearrange as needed. No problem! It's a cool project and glad I could help recruit some more writers. :)

**Comment by geraldb** [comment]
Thanks for you great help. Can't believe that all days are claimed. I leave it as is for now and see how the first week goes (and than do the double posts on maybe sundays once or twice).

**Comment by geraldb** [comment]
@philnash  I have published on day 10 the first (double) bonus post.  I'd say lets do it again with pwned, that is, you are welcome to pick any (upcoming) day and you write-up gets posted. Looking forward. Cheers. Prost.

**Comment by geraldb** [comment]
@philnash    Hello, just a reminder - no worries - no pressure - I am happy to publish your write-up of pwned in any of the upcoming days (left). Last day is the 25th. Let me / us know how is it going?  Again thanks for taking the time highlighting the pwned gem. Cheers. Prost.

**Comment by geraldb** [comment]
@philnash   Looks like I am talking to myself.   You are more than welcome to get your pwned Gem write-up published any day  - 3 more days to go / chose!    Dec 25th is that last day until next year. Cheers. Prost.

**Comment by geraldb** [comment]
The end. Thanks. See you next year. Prosit 2021!

**Comment by geraldb** [comment]
@swanson I hope this message will reach you - Thanks again for your great ruby advent calendar support / help  and thanks again for signing up all those rubyists and bringing in gem write-ups (incl. leading by example with your own write-ups incl. the kick-off post).   Happy holidays. Merry christmas. Cheers. Prosit 2021!

**Comment by swanson** [comment]
@geraldb Merry Christmas to you as well. Happy to help, it was fun! Thank you for your daily work in editing and posting. ❤️

**Comment by swanson** [comment]
![image](https://user-images.githubusercontent.com/56947/103139265-736e7180-46a8-11eb-8446-67238342f259.png)

Huge success for the calendar, nearly 25,000 people saw it!
