### ISSUE TITLE
Blockchain Day 1 - Crypto Mining gems

### ISSUE THREAD

**Issue by logicminds** [planetruby/gems#65]
## Summary

I built an entire CLI tool for managing crypto mining rigs.  My love for the CLI, simplicity of ruby and mining crypto forced me into crafting a specialize tool/library for mining crypto.  The main CLI tool is called [Crossbelt](https://crossbelt.blockops.party) (not opensource).  This CLI tool packs a lot of features used for configuring the rig, status, metrics, profit/loss statements, coin/algorithm speculation for profitability analysis and much more. I decided to pluck out portions of the code to individual gems one of which I opened sourced called [compute_unit](https://rubygems.org/gems/compute_unit).  The examples you see below utilizes the compute unit library to seed the formulas used to output the tables.

### profit
```ruby
sudo crossbelt cu profit -p 0.1 --poff=30

INDEX | NAME                           | POWER | HASH_RATE | EARNINGS_COST_RATIO | HOURLY_COST | HOURLY_EARNINGS | KWH_COST
------|--------------------------------|-------|-----------|---------------------|-------------|-----------------|---------
0     | Radeon RX 5600 OEM/5600 XT ... | 128   | 54.5 Mh   | 8.468               | 0.5 µBTC    | 4.0 µBTC        | 3.7 µBTC
1     | Radeon RX 580                  | 91    | 30.26 Mh  | 6.5                 | 0.3 µBTC    | 2.2 µBTC        | 3.7 µBTC
2     | Nitro+ Radeon RX 570/580/590   | 113   | 30.58 Mh  | 5.31                | 0.4 µBTC    | 2.2 µBTC        | 3.7 µBTC
3     | Radeon RX 5600 OEM/5600 XT ... | 129   | 54.48 Mh  | 8.292               | 0.5 µBTC    | 4.0 µBTC        | 3.7 µBTC
4     | RX 5700 XT RAW II              | 146   | 54.51 Mh  | 7.37                | 0.5 µBTC    | 4.0 µBTC        | 3.7 µBTC
5     | Radeon RX 5600 OEM/5600 XT ... | 122   | 54.44 Mh  | 8.844               | 0.5 µBTC    | 4.0 µBTC        | 3.7 µBTC
6     | Radeon RX 5600 OEM/5600 XT ... | 124   | 54.39 Mh  | 8.63                | 0.5 µBTC    | 4.0 µBTC        | 3.7 µBTC
      | Total                          | 853   | 333.16 Mh | 7.63                | 3.2 µBTC    | 24.3 µBTC       | 3.7 µBTC

```

### Status

```ruby
sudo crossbelt cu status

INDEX | NAME                           | BIOS                           | CORE_CLOCK | MEMORY_CLOCK | POWER | FAN  | CORE_VOLT | TEMP | MEM_TEMP | STATUS
------|--------------------------------|--------------------------------|------------|--------------|-------|------|-----------|------|----------|-------
GPU0  | Radeon RX 5600 OEM/5600 XT ... | 113-1E4260U-O4E                | 1365       | 900          | 98    | 2401 | 731       | 49   | 82       | 0
GPU1  | Radeon RX 580                  | 113-58085SHC1-W90              | 1190       | 2000         | 61    | 1166 | 862       | 66   | 0        | 0
GPU2  | Nitro+ Radeon RX 570/580/590   | 113-BE366EU-Z48                | 1190       | 2100         | 83    | 1659 | 862       | 51   | 0        | 0
GPU3  | Radeon RX 5600 OEM/5600 XT ... | 113-1E4260U-O4E                | 1365       | 900          | 99    | 2713 | 737       | 51   | 84       | 0
GPU4  | RX 5700 XT RAW II              | 113-180W2NAVI10XT8GD6_MS_19... | 1365       | 900          | 116   | 1614 | 712       | 53   | 82       | 0
GPU5  | Radeon RX 5600 OEM/5600 XT ... | 113-MSITV381MH.1D1         ... | 1365       | 900          | 93    | 1326 | 737       | 56   | 84       | 0
GPU6  | Radeon RX 5600 OEM/5600 XT ... | 111                            | 1375       | 900          | 94    | 1587 | 712       | 56   | 82       | 0

```

## Compute Unit Description
A ruby library that searches the linux sysfs file system for compute unit devices such as CPUS, GPUs and other ASIC compute devices. Allows programmatic access to collect real time metrics from the kernel or related driver toolchain. Is meant to be used as a toolchain for future tools. This library also makes use of opencl library and requires the opencl_ruby_ffi gem.

```ruby
require 'compute_unit/gpu'
[25] pry(main)> puts ComputeUnit::Gpu.find_all.map {|cu| { cu.uuid.to_sym => cu.name , power: cu.power, model: cu.model, vendor: cu.vendor  } }.to_yaml
---
- :GPU0: Radeon RX 5600 OEM/5600 XT / 5700/5700 XT
  :power: 98
  :model: Radeon RX 5600 OEM/5600 XT / 5700/5700 XT
  :vendor: Sapphire
- :GPU1: Radeon RX 580
  :power: 61
  :model: Radeon RX 580
  :vendor: XFX
- :GPU2: Nitro+ Radeon RX 570/580/590
  :power: 83
  :model: Nitro+ Radeon RX 570/580/590
  :vendor: Sapphire
- :GPU3: Radeon RX 5600 OEM/5600 XT / 5700/5700 XT
  :power: 99
  :model: Radeon RX 5600 OEM/5600 XT / 5700/5700 XT
  :vendor: Sapphire
- :GPU4: RX 5700 XT RAW II
  :power: 116
  :model: RX 5700 XT RAW II
  :vendor: XFX
- :GPU5: Radeon RX 5600 OEM/5600 XT / 5700/5700 XT
  :power: 87
  :model: Radeon RX 5600 OEM/5600 XT / 5700/5700 XT
  :vendor: MSI
- :GPU6: Radeon RX 5600 OEM/5600 XT / 5700/5700 XT
  :power: 94
  :model: Radeon RX 5600 OEM/5600 XT / 5700/5700 XT
  :vendor: PowerColor
```

**Comment by geraldb** [comment]
Your post is welcome if you write-up the open source compute_unit gem. You are welcome to talk about  Crossbelt but if may say not as the "core" content for the post.  Let me if that works for you or let me know what you think and day 1 is yours. Welcome. Cheers. Prost.

**Comment by logicminds** [comment]
Is there an example of a write up?  I would have wrote something up but I couldn't not find any instructions in the readme.

**Comment by geraldb** [comment]
The examples are all the 25+ from the advent calendar 2020, see <https://github.com/planetruby/gems/tree/master/2020>  or  the 10+ (older write-ups) from the gems of the week series, see <https://github.com/planetruby/gems/tree/master/week>. Every file in markdown is a write-up / article /post.

**Comment by logicminds** [comment]
Is there a special folder I need to put this in?  `blockchain/01-compute_unit.md`

**Comment by geraldb** [comment]
I see - sorry if you are the first there is no /blockchain folder on the first day.   If you send a pull request it would be great (the best) in the `_drafts`  folder/ directory (that is possible anytime).  Good point - sorry (git removes empty directories) - I added the `_drafts` folder back with your Q&A in the readme.

**Comment by geraldb** [comment]
Let me know if that makes sense or if you have other questions and if I can put you down for day 1. Cheers. Prost.

**Comment by logicminds** [comment]
Great, I'll write this up by Friday.

**Comment by geraldb** [comment]
Fantastic. Day 1 is yours. I updated the page. Looing forward. Cheers. Prost.

**Comment by geraldb** [comment]
FYI: Your write-up is now live <https://planetruby.github.io/gems/blockchain/01-compute-unit>. Thanks again. Prosit 2021! Cheers. Prost.
